version: '3.5'

services:
  db_auth:
    container_name: db_auth
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=root
    image: postgres:14.3-alpine
    volumes:
      - db_auth_vol:/var/lib/postgresql/data/:rw

volumes:
  db_auth_vol: {}